spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fastAdmin?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: root
    password:
    druid:
      maxActive: 10
      initialSize: 1
      minIdle: 1
      maxWait: 60000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat, wall
      validationQuery: select 1
      poolPreparedStatements: true
      minEvictableIdleTimeMillis: 300000
      timeBetweenEvictionRunsMillis: 60000
      maxPoolPreparedStatementPerConnectionSize: 20
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        hbm2ddl:
          auto: update
  #配置redis数据库连接
  redis:
    host: 192.168.1.10
    port: 6379
    jedis:
      pool:
        max-idle: 20
        min-idle: 1
        max-active: 20
    database: 0 #默认是索引为的0的数据库
    password:

# 屏蔽 包 输出日志(示例)
logging:
  level:
    org.fei.admin.app.dto: 'off'
  pattern:
    level:

# 微信
wechar:
  appId: wx1d64330fd2b154b0
  secret: 36b5b2e2c3e2ba13e2a30788f97c7220
  token: xfwlxfwl
  aesKey:
