# 内置 tomcat 服务器配置
server:
  port: 8090 # 指定端口
  servlet:
    context-path: /admin # 指定访问上下文路径(访问时要在端口后面加上这个路径)
  address: 0.0.0.0 # 绑定本地IP(mac os 环境下不设置无法在局域网中访问)

# spring 配置
spring:
  # 项目环境配置
  profiles:
    active: @profiles.active@ # 这个变量的值取决于 maven 中的环境变量的值
  # 发送邮件
  mail:
    host: smtp.qq.com
    username: 1748690658@qq.com
    password: dfzgicqkmyfsdjbg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  # 缓存
  cache:
    cache-names: menus_cache,role_cache
    redis:
      time-to-live: 1800s
# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 86400000
  tokenHead: "Bearer "

# 微信
wechar:
  appId: wx1d64330fd2b154b0
  secret: 36b5b2e2c3e2ba13e2a30788f97c7220
  token: xfwlxfwl
  aesKey:
